import { notFound } from "next/navigation";
import Link from "next/link";
import { db } from "@/lib/db/index";
import { videos } from "@/lib/db/schema";
import { eq } from "drizzle-orm";

export const dynamicParams = true;

export async function generateStaticParams() {
  if (!process.env.POSTGRES_URL) return [];
  const allVideos = await db.select({ vidId: videos.vidId }).from(videos);
  return allVideos.map((v) => ({ vid_id: v.vidId }));
}

function timestampToSeconds(ts: string): number {
  const parts = ts.split(":").map(Number);
  if (parts.length === 2) return parts[0] * 60 + parts[1];
  if (parts.length === 3) return parts[0] * 3600 + parts[1] * 60 + parts[2];
  return 0;
}

export default async function VideoPage({
  params,
}: {
  params: Promise<{ vid_id: string }>;
}) {
  const { vid_id } = await params;
  const video = await db.query.videos.findFirst({
    where: eq(videos.vidId, vid_id),
  });

  if (!video) notFound();

  const summary = video.summary;

  return (
    <div className="max-w-2xl mx-auto">
      <Link
        href="/"
        className="inline-flex items-center gap-1 text-sm text-zinc-500 hover:text-zinc-700 dark:hover:text-zinc-300 mb-6"
      >
        ← Back
      </Link>

      <div className="aspect-video w-full rounded-xl overflow-hidden bg-zinc-100 dark:bg-zinc-800 mb-6">
        <iframe
          src={`https://www.youtube.com/embed/${video.vidId}`}
          title={video.title}
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowFullScreen
          className="w-full h-full"
        />
      </div>

      <div className="mb-6">
        <h1 className="text-2xl font-bold tracking-tight mb-1">{video.title}</h1>
        <p className="text-sm text-zinc-500 dark:text-zinc-400">
          {video.date.toLocaleDateString("en-US", {
            year: "numeric",
            month: "long",
            day: "numeric",
          })}
        </p>
      </div>

      {summary ? (
        <div className="flex flex-col gap-6">
          {summary.oneLiner && (
            <p className="text-zinc-700 dark:text-zinc-300 text-base italic border-l-4 border-zinc-300 dark:border-zinc-700 pl-4">
              {summary.oneLiner}
            </p>
          )}

          {summary.categories && summary.categories.length > 0 && (
            <div className="flex flex-wrap gap-2">
              {summary.categories.map((cat) => (
                <span
                  key={cat}
                  className="text-sm px-3 py-1 rounded-full bg-zinc-100 dark:bg-zinc-800 text-zinc-600 dark:text-zinc-400"
                >
                  {cat}
                </span>
              ))}
            </div>
          )}

          {summary.keyTakeaways && summary.keyTakeaways.length > 0 && (
            <div>
              <h2 className="font-semibold text-lg mb-3">Key Takeaways</h2>
              <ul className="flex flex-col gap-3">
                {summary.keyTakeaways.map((takeaway, i) => (
                  <li key={i} className="flex gap-3 items-start">
                    <span className="flex-shrink-0 w-6 h-6 rounded-full bg-zinc-100 dark:bg-zinc-800 text-xs flex items-center justify-center font-medium text-zinc-500 mt-0.5">
                      {i + 1}
                    </span>
                    <span className="flex-1 text-zinc-700 dark:text-zinc-300">
                      {takeaway.text}
                      {takeaway.timestamp && (
                        <a
                          href={`${video.url}&t=${timestampToSeconds(takeaway.timestamp)}`}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="ml-2 text-xs font-mono text-blue-500 hover:underline"
                        >
                          {takeaway.timestamp}
                        </a>
                      )}
                    </span>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      ) : (
        <p className="text-zinc-500">Summary not yet available.</p>
      )}

      <p className="mt-10 text-xs text-zinc-400 dark:text-zinc-600">
        This summary was generated by AI and may contain errors. This is an unofficial fan site not
        affiliated with Theo.
      </p>
    </div>
  );
}
